#!/bin/bash
CURR_VERSION="0.9.0"
TARGET_CONTAINER_REG="ghcr.io"
TARGET_ORG="velocitynetworkfoundation"
TARGET_REPO="packages"
CONTAINER_REPOSITORY_NAME="$TARGET_ORG/$SERVER_NAME"
AWS_REGION="us-east-1"
FINERACT_SECURITY_AUTH0_SCOPE="openid,profile"

echo "CURR_VERSION=$CURR_VERSION" >> $GITHUB_ENV
echo "TARGET_CONTAINER_REG=$TARGET_CONTAINER_REG" >> $GITHUB_ENV
echo "TARGET_ORG=$TARGET_ORG" >> $GITHUB_ENV
echo "TARGET_REPO=$TARGET_REPO" >> $GITHUB_ENV
echo "CONTAINER_REPOSITORY_NAME=$CONTAINER_REPOSITORY_NAME" >> $GITHUB_ENV
echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
echo "FINERACT_SECURITY_AUTH0_SCOPE=$FINERACT_SECURITY_AUTH0_SCOPE" >> $GITHUB_ENV