#!/bin/bash
CURR_VERSION="0.9.0"
REGISTRY_URL="https://npm.pkg.github.com/"
TARGET_CONTAINER_REG="ghcr.io"
TARGET_ORG="velocitynetworkfoundation"
TARGET_REPO="packages"
NODE_HOST="0.0.0.0"
NODE_PORT="3000"
LOG_SEVERITY="debug"
CONTAINER_REPOSITORY_NAME="$TARGET_ORG/$SERVER_NAME"
AWS_REGION="us-east-1"

echo "CURR_VERSION=$CURR_VERSION" >> $GITHUB_ENV
echo "REGISTRY_URL=$REGISTRY_URL" >> $GITHUB_ENV
echo "TARGET_CONTAINER_REG=$TARGET_CONTAINER_REG" >> $GITHUB_ENV
echo "TARGET_ORG=$TARGET_ORG" >> $GITHUB_ENV
echo "TARGET_REPO=$TARGET_REPO" >> $GITHUB_ENV
echo "NODE_HOST=$NODE_HOST" >> $GITHUB_ENV
echo "NODE_PORT=$NODE_PORT" >> $GITHUB_ENV
echo "LOG_SEVERITY=$LOG_SEVERITY" >> $GITHUB_ENV
echo "CONTAINER_REPOSITORY_NAME=$CONTAINER_REPOSITORY_NAME" >> $GITHUB_ENV
echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
