#!/bin/bash
CURR_VERSION="0.9.0"
TARGET_CONTAINER_REG="ghcr.io"
TARGET_ORG="velocitynetworkfoundation"
TARGET_REPO="packages"
CONTAINER_REPOSITORY_NAME="$TARGET_ORG/$SERVER_NAME"
AWS_REGION="us-east-1"

#!/bin/bash
VER_NUM="dev-$CURR_VERSION-build.$GITHUB_SHA_SHORT"
NPM_VER_NUM="$CURR_VERSION-build.$GITHUB_SHA_SHORT"
CONTAINER_MAIN_TAG="dev"
VNF_OAUTH_TOKENS_ENDPOINT="https://vnf-dev.us.auth0.com/oauth/token"

echo "VER_NUM=$VER_NUM" >> $GITHUB_ENV
echo "NPM_VER_NUM=$NPM_VER_NUM" >> $GITHUB_ENV
echo "CONTAINER_MAIN_TAG=$CONTAINER_MAIN_TAG" >> $GITHUB_ENV
echo "VNF_OAUTH_TOKENS_ENDPOINT=$VNF_OAUTH_TOKENS_ENDPOINT" >> $GITHUB_ENV

echo "CURR_VERSION=$CURR_VERSION" >> $GITHUB_ENV
echo "TARGET_CONTAINER_REG=$TARGET_CONTAINER_REG" >> $GITHUB_ENV
echo "TARGET_ORG=$TARGET_ORG" >> $GITHUB_ENV
echo "TARGET_REPO=$TARGET_REPO" >> $GITHUB_ENV
echo "CONTAINER_REPOSITORY_NAME=$CONTAINER_REPOSITORY_NAME" >> $GITHUB_ENV
echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
