name: velocitycareerlabs/credit-market-server Points Fineract Build

on:
  push:
    branches:
      - github-workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: kamiazya/setup-graphviz@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradlew Validation
        uses: gradle/wrapper-validation-action@v1

      - name: create the war file
        run: ./gradlew clean war


      - name: deploy the war file
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.VELOCITY_TEST_HOST_URL }}
          username: ${{ secrets.VELOCITY_TEST_SSH_USER }}
          privateKey: ${{ secrets.VELOCITY_TEST_SSH_KEY }}
          local: "fineract-provider/build/libs/fineract-provider.war"
          remote: "~/deployments/docker/fineract/fineract-provider.war"

      - name: Execute command on server
        if: endsWith(github.ref, '/github-workflow')
        run: |
          echo "VELOCITY_TEST_SSH_KEY" > key.pem
          chmod 400 key.pem
          echo "Restart docker container...!!!"
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$VELOCITY_TEST_HOST_URL 'sudo docker-compose -f deployments/docker/docker-compose.yml up --build --force-recreate --remove-orphans -d'
        env:
          VELOCITY_TEST_SSH_KEY: ${{ secrets.VELOCITY_TEST_SSH_KEY }}
          VELOCITY_TEST_HOST_URL: ${{ secrets.VELOCITY_TEST_HOST_URL }}
          VELOCITY_TEST_SSH_USER: ${{ secrets.VELOCITY_TEST_SSH_USER }}
